pipelines:
  default:
    - step:
        name: Dark
        image: python:3.10
        size: 2x 
        script:
          - echo "Starting pipeline..."
          - pip install telebot flask aiogram pyTelegramBotAPI python-telegram-bot
          - chmod +x Spike
          - nohup python3 shubh.py